### PR TITLE
Added a launch screen 

### PR DESCRIPTION
**Pull request by subhronilsaha**
### Description

Added text to the blank launch screen. 

### Type of Change:

- User Interface

### How Has This Been Tested?

Tested on iOS simulator. (iPhone 11, iPhone SE)

### Checklist:

- [ x ] My PR follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by aaryankotharii — CHANGES_REQUESTED** [review]
Hi @subhronilsaha ,firstly thank you for your interest on working on this repository. Could you please attach screenshots of the launchScreen you have made. preferable iPhone 11 and iPhone SE.

**Comment by subhronilsaha** [comment]
Here is a screenshot. It is very minimal right now but I am planning on adding a background later on.

Screenshot 2020-10-06 at 3 33 48 PM

**Comment by subhronilsaha** [comment]
Here is the screenshot on iPhone SE.

Screenshot 2020-10-06 at 3 41 48 PM

**Comment by aaryankotharii** [comment]
LGTM! Thank you for your contribution @subhronilsaha.
Approved.

**Review by aaryankotharii — APPROVED** [review]

**Pull request merged**
