### PR TITLE
Fix verbiage for proper commit messages in contributing.md

### PR DESCRIPTION
**Pull request by mikaelacaron**
### Description
The contributing file says to use present tense, but the examples were all in past tense.

### Type of Change:
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on contributing file)

### How Has This Been Tested?
No tests required

### Checklist:
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

### CODE REVIEW

**Comment by mikaelacaron** [comment]
I didn't use any kind of "parser" or "spell checker" this was noticed when I was reading the file before I began making my own changes. This isn't to be spiteful or spammy.

**Review by aaryankotharii — CHANGES_REQUESTED** [review]
Hi @mikaelacaron, the issue is indeed in line number 9. It should have said `<Verb in past tense> <Action>`. Hence the examples need to be reverted and the aforesaid line needs to be changed.

**Comment by mikaelacaron** [comment]
@aaryankotharii  Understood. I'm surprised that you're wanting the convention to be past tense. On the git website, in the [commit guidelines](https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project) the convention is to use present tense.

This is to be consistent with the commands like `git add `and `git merge`, they are in present tense and aren't "git added" or "git merged."

**Comment by mikaelacaron** [comment]
Closing this so it doesn't show up on my GitHub anymore

**Pull request closed without merging**
