### PR TITLE
Task status feature added (mark as done))

### LINKED ISSUE #38: status for tasks
**Is your feature request related to a problem? Please describe.**
Right now, when the tasks are completed, we either need to delete the task or it is still there without indication of it's status.

**Describe the solution you'd like**

- For tasks that are due one of these two status is possible - **overdue/completed** (Users can decide they need to delete them or let them stay in memory as long as they wish)

- For status for other tasks could be - **wip/open**(we can change this, i'm not sure about the naming for these categories)

### PR DESCRIPTION
**Pull request by gitanshwadhwa28**
You can keep the task and mark as done if completed instead of just deleting it ( feature in many to do applications)

### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes #38 

### Type of Change:

- Code
- Addition of new feature
- User Interface

Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-04 at 01 30 01

### CODE REVIEW

**Comment by tejuamirthi** [comment]
Hey @aaryankotharii are we proceeding with this ui?

I feel it'd be better to have different sections and display the completed tasks into that sections. In that way, we can have other possibility of having tabs below/above the search bar for different status. Like completed, overdue and inprogress or anything other we can decide. 

My point is it'd be better and to plan with what's next in mind and make it future proof if we can. I'll place my bet on writing a logic that need not be edited later on. If we could seperate out the sections now in logic, when in the future, the tabs would only require a UI change and not the logic. I hope you got the point. Would love to hear your views! You obviously could suggest a better outcome entirely.

Also @gitanshwadhwa28 good work! Keep it up. Should have shared earlier if you are contributing. Anyways glad you have contributed. Let me know what you think about the above.

**Comment by aaryankotharii** [comment]
Hi @gitanshwadhwa28 , Thank you for your interest in working on this issue. The issue you have linked this pr to does not quite solve the issue's purpose but your idea of marking a task as done is great! That said, from a ux perspective, done should be more accessible than sliding a task and then selecting done. Hence you will see a checkmark box in most to-do applications. We can also do something on the same terms.

**How to proceed further?**
- remove the done action from the sliding context menu.
- simply add a button in tableview cell to mark a task as done.

since all your functions are quite atomic we don't need to make any changes apart from the 2 mentioned above.

**example preview :**
Screenshot 2020-10-05 at 6 45 45 PM

**Review by aaryankotharii — CHANGES_REQUESTED** [review]
request a review once done :)

**Comment by aaryankotharii** [comment]
Hi @gitanshwadhwa28, since this issue has been solved in #61 , I will be closing this pull request.

**Pull request closed without merging**
